[[plugins]]
repo = 'w0ng/vim-hybrid'
hook_add = '''
  set background=dark
  colorscheme hybrid
'''

[[plugins]]
repo = 'editorconfig/editorconfig-vim'

[[plugins]]
repo = 'airblade/vim-gitgutter'

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'easymotion/vim-easymotion'
