[[plugins]]
repo = 'cohama/lexima.vim'
on_i = 1
hook_source = '''
  call lexima#add_rule({'char': '<% ', 'input_after': ' %>', 'filetype': 'eruby'})
  call lexima#add_rule({'char': '<%= ', 'input_after': ' %>', 'filetype': 'eruby'})
'''

[[plugins]]
repo = 'cespare/vim-toml'
on_ft = ['toml']
